### ISSUE TITLE
[CY-2851] Missing support for sendFinalWithProjectName

### ISSUE THREAD

**Issue by willhausman** [codacy/codacy-coverage-reporter#254]
Following the steps mentioned in [documentation](https://docs.codacy.com/coverage-reporter/adding-coverage-to-your-repository/#multiple-reports) for multiple reports, the last thing to do is send a `final` notification.  When also managing multiple projects with an API Token, the api supports sending the final notification.  The coverage reporter does not.

https://github.com/codacy/codacy-api-scala/blob/dbea2e290bf58229851c9c2e1418c53070fbff3d/src/main/scala/com/codacy/api/service/CoverageServices.scala#L76

https://github.com/codacy/codacy-coverage-reporter/blob/bdda1928207e67e08f7da8092d2203b3b9effe3c/src/main/scala/com/codacy/rules/ReportRules.scala#L273-L275

**Comment by petero-dk** [comment]
Additionally the circle-orb does not support this use case either as it only works with project api

**Comment by petero-dk** [comment]
Once this is supported in the binary, the orb can be updated to support it by using this pr #255

**Comment by machadoit** [comment]
Hi @petero-dk unfortunately we are checking some details internally regarding the API token usage, since it seems that it is only working for legacy repositories. 

But either way, can you share your use case a bit better? Our use case for the partial coverage is to send multiple reports for the same repository, not to aggregate the coverage among different ones.

**Comment by machadoit** [comment]
@willhausman we are closing this and @petero-dk contribution. Thanks for raising this up, but we are going to close this issue for now, as we don't have any ETA on when/how we want to tackle this issue
