### ISSUE TITLE
[CY-2929] Unable to Find Coverage Report

### ISSUE THREAD

**Issue by one-and-only** [codacy/codacy-coverage-reporter#259]
### Are you looking for help?

This is an issue tracker, used to manage and track the development of this [Codacy](https://www.codacy.com/) project.

It is not a platform support system. If think your problem is related with our platform at https://www.codacy.com/, please contact us through our [contact form](https://www.codacy.com/contact) or our internal chat application, visible after you login on the bottom right corner.

Keep in mind that this issue tracker is for specific problems of this project.

### Scala Version (2.10.x / etc)
`2.12.12`

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
`Ubuntu 18.04`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Successfully run Coverage Runner for Python (*Coverage.py*)
2. Have the Codacy Coverage Report Successfully Upload

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "when sending the coverage with the command (...) it returns the output error (...)"

1. Coverage Runner Successfully runs for Python (*Coverage.py*)
2. Error when running Codacy Coverage Report Uploader: `Can't detect any coverage report automatically. Specify the report with the flag -r  - (CodacyCoverageReporter.scala:25)`

### Reproducible Test Case

Look under the Test App Action: [here](https://github.com/one-and-only/numworks-math-libs/pull/10)

**Comment by franciscodua** [comment]
Hi @one-and-only 

It seems your coverage tool is not outputting a report in a format this tool recognizes.
Try outputting to a cobertura format with these instructions https://coverage.readthedocs.io/en/coverage-5.3/cmd.html#xml-reporting-coverage-xml

Also, the report should either have one of the default names, or you have to specify the report you want the tool to analyze. In [here](https://docs.codacy.com/coverage-reporter/adding-coverage-to-your-repository/) you can find the reports' names that the tool finds automatically.
If you wish to maintain the default name for the generated file, you can change your command to 
```bash
# bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r <report name>
bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
```
**Note** coverage.xml because it's the default file created by coverage.py

Let us know if this solved your problem

**Comment by one-and-only** [comment]
@franciscodua That did the trick! I was using another format and didn't know it was an issue. Thanks for your help!
