### ISSUE TITLE
Parser Error but Coverage received successfully

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [codacy/codacy-coverage-reporter#69]
After running 

`java -cp ~/Downloads/codacy-coverage-reporter-2.0.2-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r ./app/build/reports/coverage/debug/report.xml`

The log result is 
.
.
.
```
2018-02-07 11:32:06,355 %PARSER_ERROR[coloredLevel] com.codacy Parsing coverage data...
2018-02-07 11:32:06,641 %PARSER_ERROR[coloredLevel] com.codacy Uploading coverage data...
2018-02-07 11:32:08,649 %PARSER_ERROR[coloredLevel] com.codacy Coverage data uploaded. RequestSuccess(Coverage received successfully.)
```
Which is not clear, if error how is it received successfully?

**Comment by rtfpessoa** [comment]
@yael-lorenzo-olx that seems fine regarding coverage.

The problem seems related to the logger formatter. So it should not affect the functionality.

Can you confirm that it appears on the UI? If you have any problem I would suggest sending a message through `support at codacy dot com` for them to check the project since the problem does not seem to be related to this repository specifically.

**Comment by yael-lorenzo-olx** [comment]
Thanks @rtfpessoa, I am still facing other issues. I will check and let you know closing the issue. Thanks.

**Comment by yael-lorenzo-olx** [comment]
Working!
